"""empty message

Revision ID: c66fc359b500
Revises: 352b9f95f861
Create Date: 2018-12-16 20:13:12.712851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66fc359b500'
down_revision = '352b9f95f861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_created_at'), 'label', ['created_at'], unique=False)
    op.create_table('print',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_serial'), 'print', ['serial'], unique=False)
    op.create_index(op.f('ix_print_timestamp'), 'print', ['timestamp'], unique=False)
    op.create_table('print_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['print_id'], ['print.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_item_timestamp'), 'print_item', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_item_timestamp'), table_name='print_item')
    op.drop_table('print_item')
    op.drop_index(op.f('ix_print_timestamp'), table_name='print')
    op.drop_index(op.f('ix_print_serial'), table_name='print')
    op.drop_table('print')
    op.drop_index(op.f('ix_label_created_at'), table_name='label')
    op.drop_table('label')
    # ### end Alembic commands ###
