"""empty message

Revision ID: e417e6677cd7
Revises: 82a05778d507
Create Date: 2018-11-05 12:02:45.447532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e417e6677cd7'
down_revision = '82a05778d507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_type_created_at'), 'box_type', ['created_at'], unique=False)
    op.create_table('equipment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_type_created_at'), 'equipment_type', ['created_at'], unique=False)
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.String(length=255), nullable=True),
    sa.Column('old_location', sa.String(length=255), nullable=True),
    sa.Column('new_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_created_at'), 'location_history', ['created_at'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_created_at'), 'room', ['created_at'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_created_at'), 'equipment', ['created_at'], unique=False)
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_created_at'), 'rack', ['created_at'], unique=False)
    op.create_table('box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('box_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_type_id'], ['box_type.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_created_at'), 'box', ['created_at'], unique=False)
    op.create_table('hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hole_created_at'), 'hole', ['created_at'], unique=False)
    op.create_table('sample_hole_history',
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('hole_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hole_id'], ['hole.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_hole_history')
    op.drop_index(op.f('ix_hole_created_at'), table_name='hole')
    op.drop_table('hole')
    op.drop_index(op.f('ix_box_created_at'), table_name='box')
    op.drop_table('box')
    op.drop_index(op.f('ix_rack_created_at'), table_name='rack')
    op.drop_table('rack')
    op.drop_index(op.f('ix_equipment_created_at'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_room_created_at'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_location_history_created_at'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_index(op.f('ix_equipment_type_created_at'), table_name='equipment_type')
    op.drop_table('equipment_type')
    op.drop_index(op.f('ix_box_type_created_at'), table_name='box_type')
    op.drop_table('box_type')
    # ### end Alembic commands ###
